
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from customtkinter import*

import GuiFn as fn
import cv2

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./Colour")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def toQuest():
    window.destroy()
    import q2

def relative_to_code(path: str) -> Path:
    return OUTPUT_PATH / Path(path)

def add(bg,jupimg,width,heigth):
    jupbg = fn.blendWithTransparent(bg, jupimg, width, heigth, 25, 25)
    jupbg = cv2.cvtColor(jupbg, cv2.COLOR_BGRA2BGR)
    cv2.imwrite("img.png", jupbg)
    # imgedit = cv2.imread("img1.png",-1)
    global image_image_3
    image_image_3.configure(file="img.png")

def huePar(value,jupimg,bg,width,heigth):
    jupimg = fn.shifthue(jupimg,value)
    add(bg,jupimg,width,heigth)

def brightnessPar(value,jupimg,bg,width,heigth):
    jupimg = fn.change_brightness(jupimg,value)
    add(bg,jupimg,width,heigth)

def contrastPar(value,jupimg,bg,width,heigth):
    jupimg = fn.apply_brightness_contrast(jupimg,value)
    add(bg,jupimg,width,heigth)

def saturationPar(value,jupimg,bg,width,heigth):
    jupimg = fn.saturation(jupimg,value)
    add(bg,jupimg,width,heigth)

def Par(jupimg,bg,width,heigth):
    jupimg = fn.shifthue(jupimg,Hue.get())
    jupimg = fn.change_brightness(jupimg,Brightness.get())
    jupimg = fn.saturation(jupimg,Saturation.get())
    jupimg = fn.apply_brightness_contrast(jupimg,Contrast.get())
    add(bg,jupimg,width,heigth)

width = 400
heigth = 400

jupimg = cv2.imread("plantimg.png",-1)
bg = cv2.imread("bodybg.png", -1)
jupbg = fn.blendWithTransparent(bg,jupimg,width,heigth,25,25)
# jupbg = cv2.cvtColor(jupbg,cv2.COLOR_BGRA2BGR)
cv2.imwrite("img.png",jupbg)

window = Tk()

window.geometry("1024x768")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    512.0,
    393.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    763.0,
    359.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_code("img.png"))
image_3 = canvas.create_image(
    281.0,
    327.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=toQuest,
    relief="flat"
)


Hue = CTkSlider(master=window, from_=0, to=100, command=lambda x: Par(jupimg,bg,width,heigth),width=360,border_width=0,progress_color="#9747FF",button_color="#672DB2",button_hover_color="#481E7E",fg_color="#D9D9D9")
Hue.place(x=580, y=290)
Hue.set(0)

Brightness = CTkSlider(master=window, from_=-225, to=255, command=lambda x: Par(jupimg,bg,width,heigth),width=360,border_width=0,progress_color="#9747FF",button_color="#672DB2",button_hover_color="#481E7E",fg_color="#D9D9D9")
Brightness.place(x=580, y=390)
Brightness.set(0)

Contrast = CTkSlider(master=window, from_=-127, to=127, command=lambda x: Par(jupimg,bg,width,heigth),width=360,border_width=0,progress_color="#9747FF",button_color="#672DB2",button_hover_color="#481E7E",fg_color="#D9D9D9")
Contrast.place(x=580, y=504)
Contrast.set(0)

Saturation = CTkSlider(master=window, from_=-225, to=225, command=lambda x: Par(jupimg,bg,width,heigth),width=360,border_width=0,progress_color="#9747FF",button_color="#672DB2",button_hover_color="#481E7E",fg_color="#D9D9D9")
Saturation.place(x=580, y=580)
Saturation.set(0)

button_1.place(
    x=86.0,
    y=583.0,
    width=391.0,
    height=106.0
)
window.resizable(False, False)
window.mainloop()
