
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import cv2
from customtkinter import *
import GuiFn as fn

# from Saved import

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./cust")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def relative_to_code(path: str) -> Path:
    return OUTPUT_PATH / Path(path)

def relative_to_trans_imgs(path: str) -> Path:
    return OUTPUT_PATH / Path("./Transparent images") / Path(path)

def relative_to_mapp(path: str) -> Path:
    return OUTPUT_PATH / Path("./Mapprojected") / Path(path)

def toQuest():
    window.destroy()
    import q1

def choosecust(path,button,n):
    global c
    c = n
    jupimg = cv2.imread(sets[n-1][3],-1)
    bg = cv2.imread("cust/image_2.png", cv2.IMREAD_UNCHANGED)
    jupbg1 = fn.blendWithTransparent(bg, jupimg, width, heigth, 25, 25)
    cv2.imwrite("img.png", jupbg1)
    image_image_2.configure(file="img.png")
    Select(button)
def Next():
    jupimg = fn.readjupimgs(sets[c-1][0], sets[c-1][2], sets[c-1][1], sets[c-1][3], width, heigth)
    bg = cv2.imread("bodybg.png", -1)
    jupbg = fn.blendWithTransparent(bg, jupimg, width, heigth, 25, 25)
    # jupbg = cv2.cvtColor(jupbg,cv2.COLOR_BGRA2BGR)
    cv2.imwrite("plantimg.png",jupimg)
    cv2.imwrite("img.png", jupbg)
    toQuest()

window = Tk()

window.geometry("1024x768")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

width = 400
heigth = 400
# imgpath = ""

state = 0
mapproject = ["Mapprojected/mapprojected1.png",
              "Mapprojected/mapprojected2.png",
              "Mapprojected/mapprojected3.png",
              "Mapprojected/mapprojected4.png",
              "Mapprojected/mapprojected5.png",
              "Mapprojected/mapprojected6.png",
              "Mapprojected/mapprojected7.png",
              "Mapprojected/mapprojected8.png",
              "Mapprojected/mapprojected9.png"]
sets = [["jupiterImgs/set1/blue.png","jupiterImgs/set1/green.png","jupiterImgs/set1/red.png","jupiterImgs/set1/mapprojected.png"],
        ["jupiterImgs/set2/blue.png","jupiterImgs/set2/green.png","jupiterImgs/set2/red.png","jupiterImgs/set2/mapprojected.png"],
        ["jupiterImgs/set3/blue.png","jupiterImgs/set3/green.png","jupiterImgs/set3/red.png","jupiterImgs/set3/mapprojected.png"],
        ["jupiterImgs/set4/blue.png","jupiterImgs/set4/green.png","jupiterImgs/set4/red.png","jupiterImgs/set4/mapprojected.png"],
        ["jupiterImgs/set5/blue.png","jupiterImgs/set5/green.png","jupiterImgs/set5/red.png","jupiterImgs/set5/mapprojected.png"],
        ["jupiterImgs/set6/blue.png","jupiterImgs/set6/green.png","jupiterImgs/set6/red.png","jupiterImgs/set6/mapprojected.png"],
        ["jupiterImgs/set7/blue.png","jupiterImgs/set7/green.png","jupiterImgs/set7/red.png","jupiterImgs/set7/mapprojected.png"],
        ["jupiterImgs/set8/blue.png","jupiterImgs/set8/green.png","jupiterImgs/set8/red.png","jupiterImgs/set8/mapprojected.png"],
        ["jupiterImgs/set9/blue.png","jupiterImgs/set9/green.png","jupiterImgs/set9/red.png","jupiterImgs/set9/mapprojected.png"]]

glasses = ["glasses/1-removebg-preview.png",
           "glasses/2-removebg-preview.png",
           "glasses/3-removebg-preview.png",
           "glasses/4-removebg-preview.png",
           "glasses/5-removebg-preview.png",
           "glasses/6-removebg-preview.png",
           "glasses/7-removebg-preview.png",
           "glasses/8-removebg-preview.png",
           "glasses/9-removebg-preview.png"]


customimgs = mapproject


jupimg = fn.readjupimgs("blue.png","red.png","green.png","projectionmap.png",width,heigth)
bg = cv2.imread("bodybg.png", cv2.IMREAD_UNCHANGED)
jupbg = fn.blendWithTransparent(bg,jupimg,width,heigth,25,25)
# jupbg = cv2.cvtColor(jupbg,cv2.COLOR_BGRA2BGR)
print(jupbg.shape[0],",",jupbg.shape[1])
cv2.imwrite("img.png",jupbg)



# body_image_1 = PhotoImage(
#     file=relative_to_code("img.png"))
# body = canvas.create_image(
#     537.0,
#     409.0,
#     image=body_image_1,
# )


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    512.0,
    384.0,
    image=image_image_1
)
image_image_2 = PhotoImage(
    file=relative_to_code("img.png"))
image_2 = canvas.create_image(
    281.0,
    300.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    760.0,
    333.0,
    image=image_image_3
)
def Reset():
    button_1.configure(border_color="white",fg_color="#443D42")
    button_2.configure(border_color="white",fg_color="#443D42")
    button_3.configure(border_color="white",fg_color="#443D42")
    button_4.configure(border_color="white",fg_color="#443D42")
    button_5.configure(border_color="white",fg_color="#443D42")
    button_6.configure(border_color="white",fg_color="#443D42")
    button_7.configure(border_color="white",fg_color="#443D42")
    button_8.configure(border_color="white",fg_color="#443D42")
    button_9.configure(border_color="white",fg_color="#443D42")
    
  

def Select(button):
    
 
    # if n == 1:
    Reset()
    button.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 2:
    #     Reset()
    #     button_2.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 3:
    #     Reset()
    #     button_3.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 4:
    #     Reset()
    #     button_4.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 5:
    #     Reset()
    #     button_5.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 6:
    #     Reset()
    #     button_6.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 7:
    #     Reset()
    #     button_7.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 8:
    #     Reset()
    #     button_8.configure(border_color="#672DB2",fg_color="#9747FF",)
    # if n == 9:
    #     Reset()
    #     button_9.configure(border_color="#672DB2",fg_color="#9747FF",)


    
button_image_1 = PhotoImage(
    file=relative_to_code(customimgs[0]))
button_1 = CTkButton(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[0],button_1,1),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_1.place(
    x=571.0,
    y=141.0,
    width=116.0,
    height=107.0
)


button_image_2 = PhotoImage(
    file=relative_to_code(customimgs[1]))

button_2 = CTkButton(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[1],button_2,2),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_2.place(
    x=571.0,
    y=267.0,
    width=116.0,
    height=107.0
)

button_image_3 = PhotoImage(
    file=relative_to_code(customimgs[2]))

button_3 = CTkButton(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[2], button_3, 3),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)

button_3.place(
    x=571.0,
    y=393.0,
    width=116.0,
    height=107.0
)

button_image_4 = PhotoImage(
    file=relative_to_code(customimgs[3]))
button_4 = CTkButton(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[3],button_4,4),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)

button_4.place(
    x=703.0,
    y=141.0,
    width=116.0,
    height=107.0
)

button_image_5 = PhotoImage(
    file=relative_to_code(customimgs[4]))

button_5 = CTkButton(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[4],button_5,5),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_5.place(
    x=703.0,
    y=267.0,
    width=116.0,
    height=107.0
)

button_image_6 = PhotoImage(
    file=relative_to_code(customimgs[5]))

button_6 = CTkButton(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[5],button_6,6),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_6.place(
    x=703.0,
    y=393.0,
    width=116.0,
    height=107.0
)

button_image_7 = PhotoImage(
    file=relative_to_code(customimgs[6]))

button_7 = CTkButton(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[6],button_7,7),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)

button_7.place(
    x=835.0,
    y=141.0,
    width=116.0,
    height=107.0
)

button_image_8 = PhotoImage(
    file=relative_to_code(customimgs[7]))

button_8 = CTkButton(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[7],button_8,8),

    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_8.place(
    x=835.0,
    y=267.0,
    width=116.0,
    height=107.0
)

button_image_9 = PhotoImage(
    file=relative_to_code(customimgs[8]))

button_9 = CTkButton(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: choosecust(customimgs[8],button_9,9),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
button_9.place(
    x=835.0,
    y=393.0,
    width=116.0,
    height=107.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda :Next(),

)
button_10.place(
    x=86.0,
    y=571.0,
    width=391.0,
    height=106.0
)

choosecust(customimgs[0],button_1,1)


x, y = 0, 0
# def motion(event):
#     # global x, y
#     x, y = event.x, event.y
#     print('{}, {}'.format(x, y))
#
# window.bind('<Motion>', motion)

def place(event):
    x, y = event.x, event.y
    if x > 51 and x < 511-131 and y > 67 and y < 533-91 :
        x = x - 51
        y = y - 67
        cust = cv2.imread(imgpath, -1)
        custjup = fn.blendWithTransparent(jupbg, cust, 131, 91, x-int(cust.shape[0]/2), y-int(cust.shape[0]/2))
        custjup = cv2.cvtColor(custjup, cv2.COLOR_BGRA2BGR)
        cv2.imwrite("img2.png", custjup)
        global image_image_2
        image_image_2.configure(file="img2.png")




cust = cv2.imread("Transparent images/1-removebg-preview.png",-1)
window.bind('<Button>',place)

window.resizable(False, False)
window.mainloop()
