
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from customtkinter import*

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./draw")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x768")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    512.0,
    393.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    281.0,
    327.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=86.0,
    y=583.0,
    width=391.0,
    height=106.0
)

Draw = CTkButton(

    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("draw"),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
Draw.place(
    x=720.0,
    y=300.0,
    width=116.0,
    height=107.0
)

DrawO = CTkButton(

    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("drawO"),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
DrawO.place(
    x=720.0,
    y=141.0,
    width=116.0,
    height=107.0
)

Erase = CTkButton(

    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("erase"),
    text="",
    relief="flat",
    corner_radius=5,
    border_width=10,
    border_color="white",
    fg_color="#443D42",
    hover=False
)
Erase.place(
    x=720.0,
    y=459.0,
    width=116.0,
    height=107.0
)
window.resizable(False, False)
window.mainloop()
