
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,filedialog
import cv2
import vars

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./endgame")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def relative_to_code(path: str) -> Path:
    return OUTPUT_PATH / Path(path)

def directory():
    filepath=filedialog.asksaveasfilename(initialdir=r"F:\python\pythonProject",
                                    title="Dialog box")
    img= cv2.imread("img.png",-1)
    cv2.imwrite(filepath+".png",img)
    canvas.configure(text="GAME OVER")


window = Tk()

window.geometry("1024x768")
window.configure(bg = "#000000")





canvas = Canvas(
    window,
    bg = "#000000",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    512.0,
    393.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_code("img.png"))
image_2 = canvas.create_image(
    512.0,
    364.0,
    image=image_image_2
)



button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=directory,
    relief="flat"
)
button_1.place(
    x=317.0,
    y=621.0,
    width=391.0,
    height=106.0
)

if vars.win:
    ctext = "YOU DID It"
else:
    ctext = "GAME OVER"

canvas.create_text(
    404.0,
    65.99999999999997,
    anchor="nw",
    text=ctext,
    fill="#FFFFFF",
    font=("GRANDGALAXY", 24 * -1)
)

window.resizable(False, False)
window.mainloop()
